#!/usr/bin/env ruby

# Copyright [2021] [sum.cumo Sapiens GmbH]

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# frozen_string_literal: true

require_relative 'lib/parser'
require_relative 'lib/exceptions'
require_relative 'lib/configuration_reader'
require_relative 'lib/api'
require 'pp'

puts "            ++++ Have I been pwned? ++++      \n\n"

ARGV[0] = '-h' if ARGV[0].nil?
params = Parser.execute

api = Api.new(params)
api.execute

puts api.json_result

# api.json_result.each do |result|
#   next if result[:Domain].empty?
#   url = "https://www.#{result[:Domain]}"
#   `pageres #{url} 1024x768 --filename='screenshots/<%= url %>' `
# end




